### ISSUE TITLE
JO, Gahyung (조가형) - Lodged 2019/12/13

### ISSUE THREAD

**Issue by mikesyoon** [mikesyoon/MYL-immigration#1089]

**Comment by mylawlihua** [comment]
30/08/2021@11am
queue / Manukau / cn: 57613854 / an: 19315370

**Comment by mylawlihua** [comment]
22/09/2021@10:48am
cn: 57613854 / an: 19315370
queue / manukau

**Comment by mylawlihua** [comment]
20/10/2021@9:43am
cn: 57613854 / an: 19315370
queue / manukau
