### ISSUE TITLE
ENZOL - BANIQUED, Ryan - Lodged 2019/12/24

### ISSUE THREAD

**Issue by mikesyoon** [mikesyoon/MYL-immigration#1129]

**Comment by mylawlihua** [comment]
12/08/2021@9:45am
Manuka branch  / queue

**Comment by mylawlihua** [comment]
22/09/2021@10:51am
an: 19357706
Manuka branch / queue

**Comment by mylawlihua** [comment]
20/10/2021@9:47am
an: 19357706
Manukau / queue
