### ISSUE TITLE
BORTHWICK , Andrew 

### ISSUE THREAD

**Issue by mikesyoon** [mikesyoon/MYL-immigration#116]

**Comment by Chocolettet** [comment]
Met with Andrew
Keen to proceed

**Comment by Chocolettet** [comment]
Sent LOE, checklists etc.
Waiting for client's documents to progress

**Comment by Chocolettet** [comment]
Request for further information 
status, skill exp, current exp, qual

**Comment by Chocolettet** [comment]
Andrew provided information
Application 90% completed
MY to check
