### ISSUE TITLE
MRNZ - JIN, Huashun (김화순) - $26 - 170pts

### ISSUE THREAD

**Issue by mylawmy** [mikesyoon/MYL-immigration#1238]

**Comment by mylawminha** [comment]
영주권이 2년정도로 너무 오래걸려서 아이랑 가족들이 중국에 있고 보고싶고 힘들어서 (이미 1년넘게 못만남) 포기하고 중국을 돌아가야 하나 하고 고민중인데. EOI만 재개되도 괜찮을거같은데 EOI도 오래걸려서 고민이 된다고 함. 
EOI 재개 된다는 소식이 나오면 그때 계약하고 인보이스 페이하고 진행하고 싶다고 연락옴
