### ISSUE TITLE
PARK, Yeon Mee (박연미) - Lodged 2020/09/04

### ISSUE THREAD

**Issue by mylawmy** [mikesyoon/MYL-immigration#1244]

**Comment by mylawmy** [comment]
Dongsik visa expires soon

**Comment by mylawmy** [comment]
@mylawlihua check information missing and list up questions in Korean to send to clients ta

**Comment by mylawlihua** [comment]
09 Aug 2021@11am
Yeon Mee Park
Makuka Branch/queue (hopefully this mth)

**Comment by mylawlihua** [comment]
20/10/ 2021@9:52am
Yeon Mee Park
Makukau Branch/queue
