### ISSUE TITLE
MRNZ - CHOI, Jihoon (최지훈) - Lodged 2021/09/21

### ISSUE THREAD

**Issue by mylawmy** [mikesyoon/MYL-immigration#1343]
INZ Recevied on 23/09/2021

**Comment by mylawminha** [comment]
2021년 6월 1일 노트 
최지훈님
WTR 비자 6개월 자동연장->2021년 12월 21일까지 
중간에 업무 쉰 적 있고, 세금 안낸 내역 등 있어서 8월말에 RFW 신청하기로 했습니다

**Comment by mylawlihua** [comment]
21 OCT 2021@10:20am
CN 49466963
AN 20510599
queue

**Comment by mylawlihua** [comment]
04/11/2021@10:30am
CN 49466963
AN 20510599
queue / Northern Region Documentation Branch
recevied 23/09/2021
