### ISSUE TITLE
MRNZ - KIM, Myongsoung (김명성) - Lodged 2021/08/02

### ISSUE THREAD

**Issue by mylawmy** [mikesyoon/MYL-immigration#1371]

**Comment by mylawmy** [comment]
@mylawminha pls provide update on progress

**Comment by mylawlihua** [comment]
23/08/21
Syoung young Soung	officer	Wellington	AN: 20420209		Asha Prasad	asha.prasad@mbie.govt.nz
Yejun Soung	queue	Wellington	AN: 20420212			
Yejin Soung	queue	Wellington	AN: 20420211   CN: 544043339
