### ISSUE TITLE
SUN, Liangliang Leanne - Lodged 2019/11/01

### ISSUE THREAD

**Issue by mylawmy** [mikesyoon/MYL-immigration#1396]

**Comment by mylawlihua** [comment]
02/09/2021 @10:06am
cn 61615530 / an 19150742
allocated on: 13/08/2021  
pre assessment at this stage.
Shaima Amir: shaima.amir@mbie.govt.nz

**Comment by mylawlihua** [comment]
01/11/2021 Yao Wu
eMedi: 20/03/2019
Xray: 08/02/2017
PC: 03/07/2019
