### ISSUE TITLE
IM, Sungtaek (임성택) - Lodged 2021/08/09

### ISSUE THREAD

**Issue by mylawmy** [mikesyoon/MYL-immigration#1398]

**Comment by mylawlihua** [comment]
1. 주신청자 형제: SUNGHO LIM  / SUNGWOO LIM: 생일 같음. 트윈??
2. I3: What date was your work visa first granted?
3. I8: Give details of your employer(s) since your talent work visa was granted:
4 .I9: Is registration required in NZ to practise in the occupation you are employed in? eg: water proofing license

**Comment by mylawlihua** [comment]
27/09/2021@10:36am
cn: 56471292 an: 20434648
queue / NADO
