### ISSUE TITLE
MRNZ - OH, Kyung Ok (오경옥) - Lodged 2021/09/07

### ISSUE THREAD

**Issue by mylawlihua** [mikesyoon/MYL-immigration#1418]

**Comment by mylawmy** [comment]
@mylawminha pls provide update on progress

**Comment by mylawlihua** [comment]
web form: complet

**Comment by mylawmy** [comment]
@mylawlihua 윤은빈 윤서빈 비자 신청서 다 작성하시면 알려주세

**Comment by mylawlihua** [comment]
@mylawmy 윤은빈 윤서빈 비자 신청서 다  했습니다.

**Comment by mylawmy** [comment]
@mylawminha waiting for daughter Eunbeen Yun's CXR result
