### ISSUE TITLE
LONCARIC, Marko - Lodged 2021/07/07 - Vy Phan

### ISSUE THREAD

**Issue by mylawmy** [mikesyoon/MYL-immigration#1438]

**Comment by mylawmy** [comment]
@mylawlihua check with client where things are at, with collecting and sending us the supporting documents

**Comment by mylawmy** [comment]
@mylawlihua pls check my instructions again

**Comment by mylawlihua** [comment]
23/08/21
Ho Yen Vy Phan / Wellington / AN: 20376365
officer: Flossie Smith (flossie.smith@mbie.govt.nz)
