### ISSUE TITLE
JEONG, Jaeyeong (정재영) - Lodged 2021/08/03

### ISSUE THREAD

**Issue by mylawlihua** [mikesyoon/MYL-immigration#1441]

**Comment by mylawmy** [comment]
@mylawminha pls provide update on progress

**Comment by mylawminha** [comment]
정재영은 누군지 모르겠는데요?

Kind regards,
Minha Jang
Immigration Executive
[mylaw-logo-3]
Auckland | Candida Building 4, Level 3, 61 Constellation Drive, Auckland 0632
Christchurch | Level 1, 95 Riccarton Road, Riccarton, Christchurch 8011
P O Box 8022, Christchurch 8440
Tel. 03 668 3262 | Mob. 027 733 0303 | Email. ***@***.******@***.***> | Web. www.immigration-lawyers.co.nz<http://www.immigration-lawyers.co.nz/> | Web(한국어). www.emin.co.nz<http://www.emin.co.nz>

AML/CFT: Commencing 1 July 2018, all lawyers are required to comply with the Anti-Money Laundering and Countering Financing of Terrorism Act 2009 (AML/CFT). Compliance with the AML/CFT legislations involves the completion of due diligence before providing services. Due diligence requirements include us asking you for your photographic identification and proof of address. With few exceptions, from 1 July 2018 we will be unable to commence work until we have completed the due diligence process.
EMAIL:  This is an e-mail from within MY Law.  MY Law does not accept responsibility for any changes to this email or its attachments made after we have transmitted it.  MY Law does not accept responsibility for attachments made by others to this email.
CONFIDENTIALITY: The contents of this e-mail (including any attachments) may be privileged and confidential.  Any unauthorised use of the contents is expressly prohibited.  If you have received this e-mail in error, please advise us by telephone immediately and then delete this e-mail together with all attachments.
VIRUSES:  All attachments have been subject to scanning by Antivirus software.  However, MY Law does not represent or warrant that files attached to this e-mail are free from computer viruses or other defects.  Any attached files are provided - and may only be used - on the basis that the user assumes all responsibility for any loss, damage or consequence resulting directly or indirectly from use of the attached files. The liability of MY Law is limited in any event to either the re-supply of the attached files or the cost of having the attached files re-supplied.
*고객분의 모든 상담과 답변은 대표 변호사 윤성식 (Michael Yoon)과 상의하에 전달해 드리는 것을 알려드립니다.

**Comment by mylawlihua** [comment]
1. Q:What position have you been offered? 
 A: Chefs assistance 351311 

comment from LH:  851311 Kitchenhand???

**Comment by mylawminha** [comment]
Hi Lihua
This client doesn't belong to me :)

**Comment by mylawlihua** [comment]
lol, you are not an assigness, I am not sure how you can see this. 
Maybe Michael will do sth about it.

**Comment by mylawlihua** [comment]
23/08/21
queue	Manukau	 AN: 20421366
