### ISSUE TITLE
MRNZ - BAE, Changwon (배창원) - Lodged 2021/09/20

### ISSUE THREAD

**Issue by mylawlihua** [mikesyoon/MYL-immigration#1471]

**Comment by mylawmy** [comment]
@mylawminha 페이 받았습니다~ 다음 단계 진행부탁합니다

**Comment by mylawlihua** [comment]
Myeonghwa (partner) visa status:
partnership visa  end 02/04/2021

Changwon Bae wv end 02/04/2021 (extended 6mth)
