### ISSUE TITLE
GUPTA, Rishi - Lodged 2021/09/24

### ISSUE THREAD

**Issue by mylawmy** [mikesyoon/MYL-immigration#1485]

**Comment by mylawlihua** [comment]
07/10/2021@ 9:52am
an 20488779
queue/chc

**Comment by mylawlihua** [comment]
15/10/2021@11:39am
an 20488779
Henderson /queue

**Comment by mylawlihua** [comment]
19/10/2021@11:15am
elaine.robertson@mbie.govt.nz
