### ISSUE TITLE
LIM, Earvin - Lodged 2021/10/19

### ISSUE THREAD

**Issue by mylawlihua** [mikesyoon/MYL-immigration#1487]

**Comment by mylawmy** [comment]
@mylawlihua payment received - please review old file and draft email to client with checklist etc - then email to me. Ta

**Comment by mylawlihua** [comment]
eMedi: 29/07/2019
Xray: 29/07/2019
PC: 8/05/2019

**Comment by mylawmy** [comment]
@mylawlihua pls check with client as to how they are getting on

**Comment by mylawlihua** [comment]
inz webform done

**Comment by mylawlihua** [comment]
10/06/2022
zach.graziotti@mbie.govt.nz
