### ISSUE TITLE
MRNZ - KANG, Moonjung (강문정) - Lodged 2021/10/01

### ISSUE THREAD

**Issue by mylawlihua** [mikesyoon/MYL-immigration#1488]

**Comment by mylawmy** [comment]
@mylawminha 페이 받았습니다 웹폼 작성 요청해주세요

**Comment by mylawlihua** [comment]
INZ web form done

**Comment by mylawmy** [comment]
@mylawlihua pls prep applications and check webform

**Comment by mylawlihua** [comment]
Both Junho and Woojin:
If you are under 16 and planning to stay in New Zealand for more than 12 months, you must have permission from your parents to travel with just one parent or travel alone. Choose which option applies to you:*
1. I am not under 16
2. I am under 16 and will be staying in New Zealand with both parents
3. I am under 16 and will be staying in New Zealand with just one parent

Woojin: 
Provide your most recent overseas address:

**Comment by mylawminha** [comment]
Both Junho and Woojin:
Junho born in 2003, Woojin born in 2007 -> Only woojin needs the answer below and it is "3. I am under 16 and will be staying in New Zealand with just one parent"

If you are under 16 and planning to stay in New Zealand for more than 12 months, you must have permission from your parents to travel with just one parent or travel alone. Choose which option applies to you:*
1. I am not under 16
2. I am under 16 and will be staying in New Zealand with both parents
3. I am under 16 and will be staying in New Zealand with just one parent

Woojin:
Provide your most recent overseas address:
If there is most recent overseas address for Junho , use it same please.

**Comment by mylawmy** [comment]
@mylawminha need evidence for updated weekly hours
