### ISSUE TITLE
MRNZ - CHOI, Jihoon (최지훈) - Lodged 2021/10/26

### ISSUE THREAD

**Issue by mylawlihua** [mikesyoon/MYL-immigration#1491]

**Comment by mylawminha** [comment]
payment schedule update
1차 비자 신청 이전 – 10월 11일 정도
$2,830
네 분의 이민국 신청비용 $1680
수임료 1/3 1000+GST
 
2차 – 2주 후 10월 25일 정도
$1,180
수임료 1/3 1000+GST
Office expense 등 $30
 
3차 – 2주 후 11월 8일 정도
$1,150
수임료 1/3 1000+GST

**Comment by mylawminha** [comment]
singed LOE received

**Comment by mylawminha** [comment]
Paid 
1차 비자 신청 이전 – 10월 11일 정도
$2,830
네 분의 이민국 신청비용 $1680
수임료 1/3 1000+GST

**Comment by mylawlihua** [comment]
04/11/2021@10:44am
Northern Region Documentation Branch
AN: 20532610
medical / waitting for further requirement 
medical done on 13/07/2021
