### ISSUE TITLE
WANG, Pengcheng

### ISSUE THREAD

**Issue by mylawmy** [mikesyoon/MYL-immigration#1518]

**Comment by mylawlihua** [comment]
14/12/2021@10:12am
cn54846765
an20587511
alec.thomas@mbie.govt.nz

**Comment by mylawmy** [comment]
pending NZPC and NSC

**Comment by mylawmy** [comment]
9 Jan NZPC received

**Comment by mylawlihua** [comment]
25/02/2022@11:02am
pending nsc
joella.lee-lo@mbie.govt.nz
