### ISSUE TITLE
MARWAHA, Chetan

### ISSUE THREAD

**Issue by mylawmy** [mikesyoon/MYL-immigration#1522]

**Comment by mylawlihua** [comment]
14/12/2021@9:57am
cn63760341
an20584114
8/12/2021 wait nz pc
shan.bian@mbie.govt.nz

**Comment by mylawlihua** [comment]
20/01/2022@10:30am
NZPC received: 22 Dec
 National Security Check requested: 18 Jan

**Comment by mylawlihua** [comment]
24/01/2022
reply from IO: The application has been referred for a third party check. 
This appears to be the process requested and undertaken by the third party. Unfortunately we do not know exactly when the process will be completed, as such I am not able to provide you with a timeframe.

**Comment by mylawlihua** [comment]
8/2/2022@11:43
no update

**Comment by mylawlihua** [comment]
25/02/2022@10:50am
no update
