### ISSUE TITLE
LONCARIC, Marko - EOI 2021/05/08 - 2022/02/27 - 2671316

### ISSUE THREAD

**Issue by mylawmy** [mikesyoon/MYL-immigration#1523]

**Comment by mylawlihua** [comment]
04 Mar 2022@1pm
CN56893652
Man Branch
NZPC pending
sanuel.pene@mbie.govt.nz

**Comment by mylawlihua** [comment]
11/03/2022@1:23pm
chc branch/pending nzpc/reassess medical
10 mar: assessment done
 dhianne.estinozo@mbie.govt.nz

**Comment by mylawlihua** [comment]
21/03/2022@11:26am
final processing

**Comment by mylawlihua** [comment]
30/03/2022@10:40am
not been finalised
