### ISSUE TITLE
CUI, Guofeng

### ISSUE THREAD

**Issue by mylawmy** [mikesyoon/MYL-immigration#1528]

**Comment by mylawlihua** [comment]
14/12/2021@10:37am
cn65613752
an20590731
nado

**Comment by mylawmy** [comment]
6 jan note
NZPC clear for both PA and SA
NSC pending

**Comment by mylawlihua** [comment]
21/01/2022@9:49am
NSC clear, wait for IO

**Comment by mylawlihua** [comment]
10/02/2022@10:22am
pending NSC

**Comment by mylawlihua** [comment]
25/02/2022 @10:57am
pending NSC
kushagra.krishna@mbie.govt.nz

**Comment by mylawlihua** [comment]
11/03/2022@1:21am
no updates
