### ISSUE TITLE
SUN, Liangliang

### ISSUE THREAD

**Issue by mylawmy** [mikesyoon/MYL-immigration#1535]

**Comment by mylawlihua** [comment]
9/12/2021@11:31am
Application number: 20588150
Client Number: 76287048
que/documentation branch

**Comment by mylawlihua** [comment]
14/12/2021@10:30am
Application number: 20588150
Client Number: 76287048
que/documentation branch

**Comment by mylawmy** [comment]
joella lee-lo

**Comment by mylawmy** [comment]
NSC and NZPC all pending

**Comment by mylawlihua** [comment]
25/01/2022@10:37am
Leanne:
NZPC: Yes
NSC: 14/12/2021
Emma:
NZPC: 14/12/2021 
NSC: dont need one

no IO

**Comment by mylawlihua** [comment]
25/02/2022@11am
pending nsc
joella.lee-lo@mbie.govt.nz

**Comment by mylawlihua** [comment]
4/03/2022@9:38am
case officer done all file assessment,
second person check
