### ISSUE TITLE
KUSHWAHA, Hemant

### ISSUE THREAD

**Issue by mylawlihua** [mikesyoon/MYL-immigration#1656]

**Comment by mylawlihua** [comment]
9/12/2021 @11:39am
RV2021 application numbe is 20590770
que / Document branch

**Comment by mylawlihua** [comment]
10/12/2021@9:50am
Kushwaha Hemant
cn 45342401
an 20590770

**Comment by mylawlihua** [comment]
14/12/2021@10:40am
cn 45342401
an 20590770
nado/que

**Comment by mylawmy** [comment]
6 jan - initial assessment done
pending NZPC

**Comment by mylawlihua** [comment]
20/01/2022@11am
mintu.lama@mbie.govt.co.nz (John)
17 Jan recevied NZPC

**Comment by mylawlihua** [comment]
24/01/2022
reply from IO: I am still processing this application. I am hoping to provide an update by end of next week.
