### ISSUE TITLE
OLIVEIRA, Marcus - Lodged 2020/01/24

### ISSUE THREAD

**Issue by mikesyoon** [mikesyoon/MYL-immigration#717]

**Comment by mylawlihua** [comment]
•	Passport photo
•	Police certificates
•	Emedical 
•	Bank statements 
•	Utility bills 
•	same address 
•	Photo timeline

**Comment by mylawlihua** [comment]
02/09/2021@10am
Manukau / queue / cn: 60117669 / an: 19437892
last update from Manukau branch on 16/08/2021: they just allocated the applications from 4/11/2019.
paper application, has to wait until L2.
