### ISSUE TITLE
ARRU, Alessandra - Lodged 2020/08/28

### ISSUE THREAD

**Issue by mikesyoon** [mikesyoon/MYL-immigration#836]

**Comment by mylawlihua** [comment]
15/06/2022
Man brnach / queue

**Comment by mylawlihua** [comment]
27/09/2022@10:08am
9 sep recevied email from Michael. no further comment

**Comment by mylawlihua** [comment]
19/10/2022@11:36am
man / no further updates since last call.

tarn.kaur@mbie.govt.nz

**Comment by mylawlihua** [comment]
19/10/2022: Email from INZ

Kia Ora Lihua 

Thank you for your email. 

We are currently waiting for this application to be allocated to a case officer. 
The case officer will be in touch, if any further information is required. 
Many thanks 

Kind regards
Tarn Jot Kaur  (she/her)
IMMIGRATION OFFICER | Manukau Area Office 

Border and Visa Operations, Immigration New Zealand
Ministry of Business, Innovation and Employment

Email: Tarn.Kaur@mbie.govt.nz

**Comment by mylawlihua** [comment]
03/11/2022@9:57am
margaret.zhao@mbie.govt.nz
