### ISSUE TITLE
KUSHWAHA, Hemant - Lodged 2019/11/04

### ISSUE THREAD

**Issue by mikesyoon** [mikesyoon/MYL-immigration#905]

**Comment by mylawmy** [comment]
lodged es wv

**Comment by mylawsam** [comment]
Called INZ about SMC - still in queue - emailed Hemant to let him know

**Comment by mylawlihua** [comment]
22/09/2021@10:25am
an: 19151104
Su choi (su.choi@mbie.govt.co.nz) allocated 22/09/2021
