### ISSUE TITLE
KUMAR, Pawan (on behalf of Koini Nareka) 

### ISSUE THREAD

**Issue by Chocolettet** [mikesyoon/MYL-immigration#96]

**Comment by Chocolettet** [comment]
Waiting for information from Koini
supporting form signed and declared

**Comment by mikesyoon** [comment]
Don't think this should be in the Now column

**Comment by Chocolettet** [comment]
It is in the name of Pawan Kumar, visitor visa for Koini. We are waiting for information. We have been engaged.

**Comment by Chocolettet** [comment]
Collating information
Emailed client today requesting for more information 
Information to be scanned together by categories at once when gathered

**Comment by Chocolettet** [comment]
Ready to lodge application 
Waiting for MY's review of application
Need to upload cover letter - edited, and for MY's approval.

**Comment by Chocolettet** [comment]
Officer came back and said that applicant has not provided information for partnership. 
Emailed to clarify whether or not there was something in particular she was asking for. Make sure she responds so that we can still request for more information from client if required. 

Due date: 22.8.2018
